In [ ]:
import pandas as pd

# Ejercicio 1

Obtener la versión de la librería pandas.

## Solución:

In [ ]:
pd.__version__

'0.24.2'

# Ejercicio 2



*   Convertir la lista dada en una estructura pandas Series. 
*   Comprueba su tamaño.
* Utiliza el comando describe() y mira para qué sirve.

In [ ]:
datos = [2, 3, 5, 7, 11]

## Solución:

In [ ]:
datos = [2, 3, 5, 7, 11]

serie = pd.Series(datos)

In [ ]:
serie

0     2
1     3
2     5
3     7
4    11
dtype: int64

In [ ]:
serie.size

5

In [ ]:
serie.describe()

count     5.000000
mean      5.600000
std       3.577709
min       2.000000
25%       3.000000
50%       5.000000
75%       7.000000
max      11.000000
dtype: float64

# Ejercicio 3

* Ahora vuelve a convertir la pandas series de antes a una lista Python.
* Comprueba su tipo con la función type()

## Solución:

In [ ]:
type(serie)

pandas.core.series.Series

In [ ]:
lista = serie.tolist()

In [ ]:
type(lista)

list

In [ ]:
lista

[2, 3, 5, 7, 11]

# Ejercicio 4

Aplicar las operaciones aritméticas básicas sobre los objetos Series dados.

Prueba a:
* Sumar
* Restar
* Multiplicar
* Dividir

In [ ]:
serie1 = pd.Series([1, 2, 3, 4, 5])
serie2 = pd.Series([9, 8, 7, 6, 5])

## Solución:

In [ ]:
serie1 + serie2

0    10
1    10
2    10
3    10
4    10
dtype: int64

In [ ]:
serie1 - serie2

0   -8
1   -6
2   -4
3   -2
4    0
dtype: int64

In [ ]:
serie1 * serie2

0     9
1    16
2    21
3    24
4    25
dtype: int64

In [ ]:
serie1 / serie2

0    0.111111
1    0.250000
2    0.428571
3    0.666667
4    1.000000
dtype: float64

# Ejercicio 5

Usar operadores relacionales para comparar los objetos Series dados.

In [ ]:
serie1 = pd.Series([1, 2, 3, 5, 7])
serie2 = pd.Series([13, 17, 11, 5, 3])

¿Qué ocurre? ¿Se comparan todos los elementos? ¿Se compara el objeto únicamente...?



```
Introduce aquí tu respuesta
```

## Solución:

In [ ]:
serie1 < serie2

0     True
1     True
2     True
3    False
4    False
dtype: bool

In [ ]:
serie1 > serie2

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [ ]:
serie1 == serie2

0    False
1    False
2    False
3     True
4    False
dtype: bool

# Ejercicio 6



*   Convertir el diccionario Python en un objeto Series.
*   Intenta imprimir un pantalla algún valor de la serie.

PD: Fíjate como accedemos al valor.

In [ ]:
datos = {'a': 10, 'b': 20, 'c': 30, 'd': 40}

## Solución:

In [ ]:
serie = pd.Series(datos)

In [ ]:
serie

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
serie['a']

10

# Ejercicio 7

Crea un array NumPy y conviertelo en un objeto Series.

In [ ]:
#Crea un array NumPy 
import numpy as np
vector =

In [ ]:
#Conviertelo en un objeto Series.

## Solución:

In [ ]:
vector

array([ 2,  3,  5,  7, 11])

In [ ]:
serie = pd.Series(vector)

In [ ]:
serie

0     2
1     3
2     5
3     7
4    11
dtype: int32

# Ejercicio 8

Cambiar el tipo de datos de un objeto Series.



*   Cambiar la siguiente serie de Strings en númerica

In [ ]:
datos = pd.Series(['100', '200', '', '300.15', '500.8'])

## Solución:

In [ ]:
datos = pd.Series(['100', '200', '', '300.15', '500.8'])

datos

0       100
1       200
2    python
3    300.15
4     500.8
dtype: object

In [ ]:
datos = pd.to_numeric(datos)

datos

0    100.00
1    200.00
2       NaN
3    300.15
4    500.80
dtype: float64

# Ejercicio 9

Obtener una columna de un objeto DataFrame como un objeto Series.

In [ ]:
datos = {'A': [1, 2, 3, 4, 5], 'B': [9, 8, 7, 6, 5], 'C': [2, 3, 5, 7, 11]}

df = pd.DataFrame(data=datos)

df

   A  B   C
0  1  9   2
1  2  8   3
2  3  7   5
3  4  6   7
4  5  5  11

## Solución:

In [ ]:
datos = pd.Series(df['A'])
type(datos)

pandas.core.series.Series

# Ejercicio 10 (Opcional)

Convertir un objeto Series con múltiples listas en un único objeto Series.

In [ ]:
datos = [['Colombia', 'Perú', 'Argentina'], ['Bolivia', 'Uruguay'], ['Chile']]

serie = pd.Series(datos)

serie

0    [Colombia, Perú, Argentina]
1             [Bolivia, Uruguay]
2                        [Chile]
dtype: object

## Solución:

In [ ]:
serie = serie.apply(pd.Series).stack().reset_index(drop=True)

In [ ]:
serie

0     Colombia
1         Perú
2    Argentina
3      Bolivia
4      Uruguay
5        Chile
dtype: object

In [ ]:
type(serie)

pandas.core.series.Series

# Ejercicio 11

Ordenar los valores de un objeto Series con el método sort_values.

In [ ]:
datos = ['1.1', 'Python', '0.5', 'pandas', '2.8']

serie = pd.Series(datos)

serie

0       1.1
1    Python
2       0.5
3    pandas
4       2.8
dtype: object

## Solución:

In [ ]:
serie = pd.Series(serie).sort_values()

In [ ]:
serie

2       0.5
0       1.1
4       2.8
1    Python
3    pandas
dtype: object

# Ejercicio 12

Agregar datos a un objeto Series existente.

* Usa el método append()
* IMPORTANTE: Si estamos trabajando con pandas series y aplicamos el método append(), espera recibir como argumento una pandas series.

In [ ]:
datos = ['Python', 'C#', 'C++', 'Java', 'PHP']

serie = pd.Series(datos)

serie

0    Python
1        C#
2       C++
3      Java
4       PHP
dtype: object

## Solución:

In [ ]:
serie = serie.append(pd.Series(['JavaScript', 'Perl']))

serie

0        Python
1            C#
2           C++
3          Java
4           PHP
0    JavaScript
1          Perl
dtype: object

# Ejercicio 13

Crear un objeto Series a partir de un filtro aplicado a otro objeto Series.

Quédate con los datos que sean menores de 6.

In [ ]:
datos = [0, 1, 7, 3, 4, 5, 6, 7, 8, 9]

serie = pd.Series(datos)

serie

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

## Solución:

In [ ]:
n = 6

serie_nueva = serie[serie < n]

serie_nueva

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

# Ejercicio 14

* Tenemos un objeto series con letras como Indices y números como valores
* Cambiar el orden del índice de un objeto Series.
* El orden tiene que ser: ['B', 'A', 'C', 'D', 'E']

PISTA: Podrías buscar en internet how to change index order series python

In [ ]:
datos = [1, 2, 3, 4, 5]

indices = ['A', 'B', 'C', 'D', 'E']

serie = pd.Series(data=datos, index=indices)

serie

A    1
B    2
C    3
D    4
E    5
dtype: int64

## Solución:

In [ ]:
serie = serie.reindex(index=['B', 'A', 'C', 'D', 'E'])

serie

B    2
A    1
C    3
D    4
E    5
dtype: int64

# Ejercicio 15

Obtener la desviación estándar y el promedio de un conjunto de datos de una serie.

In [ ]:
datos = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

serie = pd.Series(datos)

serie

0     2
1     3
2     5
3     7
4    11
5    13
6    17
7    19
8    23
9    29
dtype: int64

## Solución:

In [ ]:
serie.std()

9.024041962077378

In [ ]:
serie.mean()

12.9

# Ejercicio 16

Calcular los valores mínimo y máximo de un objeto Series.

In [ ]:
datos = [19, 2, 13, 0, 23, 29, 11, 7]

serie = pd.Series(datos)

serie

0    19
1     2
2    13
3     0
4    23
5    29
6    11
7     7
dtype: int64

## Solución:

In [ ]:
serie.min()

0

In [ ]:
serie.max()

29

# Ejercicio 17 (Opcional)

Obtener estádisticas básicas de un objeto Series con el método `describe`.

## Solución:

In [ ]:
serie.describe()

count    10.00000
mean      4.50000
std       3.02765
min       0.00000
25%       2.25000
50%       4.50000
75%       6.75000
max       9.00000
dtype: float64

## Ejercicio 19

Obtener los elementos impares de un objeto Series numérico.

In [ ]:
datos = [19, 2, 13, 0, 23, 29, 11, 7]

serie = pd.Series(datos)

serie

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Solución:

In [ ]:
impares = serie[serie % 2 == 1]

impares

1    1
3    3
5    5
7    7
9    9
dtype: int64

# Ejercicio 19 (Opcional)

Extraer los datos de un objeto Series como un objeto NumPy.

## Solución:

In [ ]:
arreglo = serie.values

arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

# Ejercicio 20

Comprobar si una serie contiene valores NaN. Ya existe una función que lo comprueba.

In [ ]:
datos = ['20', '30', '', '50', 100]

serie = pd.Series(datos)
serie = pd.to_numeric(serie)

serie

## Solución:

In [ ]:
serie.hasnans

True

# Ejercicio 21 (Opcional)

Operaciones aritméticas con métodos de la clase Series: `add`, `subtract`, `multiply`, y `divide`.

In [ ]:
serie1 = pd.Series(list(range(1, 11)))

serie1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
serie2 = pd.Series(list(range(10, 0, -1)))

serie2

0    10
1     9
2     8
3     7
4     6
5     5
6     4
7     3
8     2
9     1
dtype: int64

## Solución:

In [ ]:
serie1.add(serie2)

0    11
1    11
2    11
3    11
4    11
5    11
6    11
7    11
8    11
9    11
dtype: int64

In [ ]:
serie1.subtract(serie2)

0   -9
1   -7
2   -5
3   -3
4   -1
5    1
6    3
7    5
8    7
9    9
dtype: int64

In [ ]:
serie1.multiply(serie2)

0    10
1    18
2    24
3    28
4    30
5    30
6    28
7    24
8    18
9    10
dtype: int64

In [ ]:
serie1.divide(serie2)

0     0.100000
1     0.222222
2     0.375000
3     0.571429
4     0.833333
5     1.200000
6     1.750000
7     2.666667
8     4.500000
9    10.000000
dtype: float64

# Ejercicio 22

Eliminar los valores NaN de una serie con el método dropna.

In [ ]:
datos = ['2.3', '90', '100', np.nan, '0.5', '.9']

serie = pd.Series(datos)

serie

0       2.3
1    Python
2        90
3       100
4       NaN
5       0.5
6        .9
dtype: object

## Solución:

In [ ]:
serie = serie.dropna()

serie

0      2.3
2     90.0
3    100.0
5      0.5
6      0.9
dtype: float64

# Ejercicio 23

Reemplazar los valores NaN (null) de una serie con un valor arbitrario.

In [ ]:
datos = [1, 3, np.nan, 11, 'Python', '-0.5', np.nan]

serie = pd.Series(datos)

serie

0         1
1         3
2         7
3        11
4    Python
5      -0.5
6       NaN
dtype: object

## Solución:

In [ ]:
serie.fillna(0, inplace=True)

serie

0         1
1         3
2         7
3        11
4    Python
5      -0.5
6         0
dtype: object